spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Study/h2/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  quartz:
    scheduler-name: "MyQuartzScheduler"
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    overwrite-existing-jobs: true

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org.hibernate.sql: info
    org.hibernate.type: trace